### ISSUE TITLE
[Feature Request] Ability to Add a new item to Pocket

### ISSUE THREAD

**Issue by sinewave** [VNXtreme/node-red-contrib-pocket-api#1]
Thx for creating this node!! I was just looking for something like this for NR only to discover that none existed so I was happy to come across yours :)

Any chance you would consider implementing the ability to also Add new items to your pocket list.

Thx

**Comment by VNXtreme** [comment]
Thanks for your feedback. 

I surely will update Add functionality in the next few days.

**Comment by VNXtreme** [comment]
> Thx for creating this node!! I was just looking for something like this for NR only to discover that none existed so I was happy to come across yours :)
> 
> Any chance you would consider implementing the ability to also Add new items to your pocket list.
> 
> Thx

Hi,

I have updated the Add item node. 
Please update the package.

Happy coding.

**Comment by sinewave** [comment]
Amazing, tku!!

I'm not seeing an update available within NR or on their site... does it take a while for it catch the update?

**Comment by VNXtreme** [comment]
Sorry for my late reply.

And sorry I forgot to use this link https://flows.nodered.org/add/node to tell node-red to update node to its latest version.
You can now use the version 0.0.11.

Thank you for your feedback.
Peace

**Comment by sinewave** [comment]
Working great, thx so much for creating this node!!!
